fix(environment): always sort envVars
turnerlabs/shipit-api pull request #21
Opened 2017-08-23 21:24 UTC by jkurz

* make sure envVars are always coming back in the same order
* tests remove the sort that were there to help make the tests pass

2017-08-24 11:14 UTC, jtolsma approved these changes

2017-08-24 14:37 UTC, wilsonodk requested changes
It would seem to make more sense to have the DB sort them, versus sorting in code.

http://docs.sequelizejs.com/manual/tutorial/querying.html#ordering

2017-08-29 22:01 UTC, jkurz commented
I tried many different approaches to get orderBy to work at the DB query layer. It seems like this bug is playing a role. https://github.com/sequelize/sequelize/issues/2121

I tried the suggested approach `order: [['name', 'ASC']]` on all levels of the query object. Was not able to get it to work. I tried setting the value like `order: [['"name"', 'ASC']]`, `order:  [[model.sequalize.col('name'), 'ASC']]` and all variations of ASC and DESC. None of these worked nor did the documented approach on the sequealize site. 

I suggest we just continue with this simple in memory sort for now and if we need other items sorted we do it later.

2017-08-30 13:21 UTC, wilsonodk approved these changes

2017-08-30 17:28 UTC, merged